### ISSUE TITLE
Device commands are repeated on the device for each invocation

### ISSUE THREAD

**Issue by xraken** [sushilks/harmonyHubUtil#1]
When I try to send a device specific command say "DirectionUp" for TV while within a Menu I see the DirectionUp getting hit 3-4 times. When I try the TV Mute command I can see the TV toggle mute a couple of times before it settles down. This behavior is similar to just holding down a remote button. I wonder if some additional parameter needs to be sent to the Hub to ensure that the command is invoked just once. BTW, these commands work fine when using the Logitech provided Android app.

**Comment by sushilks** [comment]
I have not seen this behaviour on my setup. 
This will require some debugging on your environment.
The harmonyHubUtil is mostly a wrapper around the package "harmonyhubjs-client" which provides all the low level implementation on the commands. it's possible there might be something that changed on dependent packaged,  recently there was a dependency that broke the system (https://github.com/sushilks/harmonyHubCLI/issues/1) 
You will need to do some additional debug and post back results.

**Comment by sushilks** [comment]
@xraken any updates from your debug ?

**Comment by xraken** [comment]
Sorry, should have replied sooner. I was not able to get to the bottom of the difference between the commands when issuing through the remote (where it works fine) vs. sending the same command via your utility. However, I was messing around with the timing options for the TV device on the remote app and it somehow fixed the problem. I just left it at that.

**Comment by sushilks** [comment]
Ok, Sounds like it's resolved,Closing the issue.
